# .github/workflows/build.yml

name: Build sOCRate Executables

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # --- JOB 1 : CONSTRUCTION POUR WINDOWS (INCHANGÉ) ---
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Tesseract OCR
        run: choco install tesseract-ocr --params='"/l fra,eng,por"' -y
      - name: Build Windows executable
        run: |
          pyinstaller --windowed --onefile --name sOCRate `
          --icon=assets/icon.ico `
          --add-data "C:/Program Files/Tesseract-OCR;Tesseract-OCR" `
          socrate.py
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: sOCRate-Windows-Executable
          path: dist/sOCRate.exe

  # --- JOB 2 : CONSTRUCTION POUR MACOS (AVEC HABILITATIONS) ---
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Tesseract OCR via Homebrew
        run: brew install tesseract tesseract-lang
      - name: Build macOS application
        run: |
          # On trouve dynamiquement le chemin d'installation de Tesseract
          TESSERACT_PATH=$(brew --prefix tesseract)
          pyinstaller --windowed --name sOCRate \
          --icon=assets/icon.icns \
          --add-data "$TESSERACT_PATH:Tesseract-OCR" \
          --osx-entitlements-file entitlements.plist \
          socrate.py
      - name: Package macOS application
        run: |
          zip -r sOCRate-macOS.zip dist/sOCRate.app
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: sOCRate-macOS-App
          path: sOCRate-macOS.zip