# .github/workflows/build.yml

name: Build sOCRate Application

on:
  push:
    branches: [ "main" ] # Déclenche la compilation à chaque push sur la branche main
  workflow_dispatch: # Permet de lancer manuellement la compilation depuis l'interface GitHub

jobs:
  build_macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies (Homebrew)
      run: |
        brew install tesseract tesseract-lang

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller # On installe PyInstaller sur le runner

    - name: Build macOS Application
      run: |
        # On doit trouver où Homebrew a installé Tesseract pour le copier.
        TESSERACT_PATH=$(brew --prefix tesseract)
        
        pyinstaller socrate_app.py --noconfirm --onedir --windowed \
          --name "sOCRate" \
          --icon "icon_settings.png" \
          --add-data "icon_settings.png:." \
          --add-data "${TESSERACT_PATH}/bin:Tesseract-OCR/bin" \
          --add-data "${TESSERACT_PATH}/lib:Tesseract-OCR/lib" \
          --add-data "${TESSERACT_PATH}/share/tessdata:Tesseract-OCR/share/tessdata" \
          --osx-bundle-identifier "com.votreNom.socrate" \
          --osx-entitlements-file "entitlements.plist"

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sOCRate-macOS
        path: dist/sOCRate.app

  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Download and Extract Tesseract for Windows
      shell: pwsh
      run: |
        # URL vers une version stable et fiable de Tesseract pour Windows
        $tesseractUrl = "https://github.com/UB-Mannheim/tesseract/releases/download/v5.3.3/tesseract-ocr-w64-setup-v5.3.3.20231005.exe"
        Invoke-WebRequest -Uri $tesseractUrl -OutFile tesseract_setup.exe
        # Installation silencieuse de Tesseract
        Start-Process -FilePath ".\tesseract_setup.exe" -ArgumentList "/S" -Wait
        # Le chemin par défaut de l'installation silencieuse
        $env:TESS_PATH="C:\Program Files\Tesseract-OCR"

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Windows Application
      run: |
        # Le chemin est fixé par l'installeur Tesseract
        $TESS_PATH="C:\Program Files\Tesseract-OCR"

        pyinstaller socrate_app.py --noconfirm --onedir --windowed `
          --name "sOCRate" `
          --icon "icon_settings.png" `
          --add-data "icon_settings.png;." `
          --add-data "$TESS_PATH;Tesseract-OCR"

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sOCRate-Windows
        path: dist/sOCRate