# .github/workflows/build.yml

name: Build sOCRate Executables

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # --- JOB 1 : CONSTRUCTION POUR WINDOWS (INCHANGÉ ET CORRECT) ---
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Tesseract OCR
        run: choco install tesseract-ocr --params='"/l fra,eng,por"' -y
      - name: Build Windows executable
        run: |
          pyinstaller --windowed --onefile --name sOCRate `
          --icon=assets/icon.ico `
          --add-data "C:/Program Files/Tesseract-OCR;Tesseract-OCR" `
          socrate.py
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: sOCRate-Windows-Executable
          path: dist/sOCRate.exe

  # --- JOB 2 : CONSTRUCTION POUR MACOS (SOLUTION DÉFINITIVE) ---
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Install Tesseract OCR via Homebrew
        run: brew install tesseract tesseract-lang

      - name: Build macOS application
        run: |
          TESSERACT_PREFIX=$(brew --prefix tesseract)
          pyinstaller --windowed --name sOCRate \
          --icon=assets/icon.icns \
          --add-data "$TESSERACT_PREFIX:Tesseract-OCR" \
          --osx-entitlements-file entitlements.plist \
          socrate.py

      # --- ÉTAPE FINALE ET CRUCIALE : CORRECTION DES CHEMINS DES BIBLIOTHÈQUES ---
      - name: Fix Tesseract dynamic library paths
        run: |
          # Définit le chemin où se trouvent les binaires et bibliothèques dans le .app
          APP_RESOURCES="dist/sOCRate.app/Contents/Resources/Tesseract-OCR"
          TESS_BIN="$APP_RESOURCES/bin/tesseract"
          TESS_LIBS_DIR="$APP_RESOURCES/lib"
          
          # 1. Donne la permission d'exécution
          chmod +x "$TESS_BIN"
          
          # 2. Boucle sur toutes les bibliothèques (.dylib) et réécrit leurs chemins
          for lib in $(find "$TESS_LIBS_DIR" -name '*.dylib'); do
              echo "Processing library: $lib"
              # a) Change l'ID de la bibliothèque pour qu'il soit relatif
              install_name_tool -id "@rpath/$(basename "$lib")" "$lib"
              # b) Change les références aux AUTRES bibliothèques Tesseract pour qu'elles soient relatives
              for deplib in $(otool -L "$lib" | grep '/opt/homebrew' | awk '{print $1}'); do
                  install_name_tool -change "$deplib" "@rpath/$(basename "$deplib")" "$lib"
              done
          done

          # 3. Réécrit les chemins dans l'exécutable tesseract principal
          echo "Processing main executable: $TESS_BIN"
          for deplib in $(otool -L "$TESS_BIN" | grep '/opt/homebrew' | awk '{print $1}'); do
              install_name_tool -change "$deplib" "@rpath/$(basename "$deplib")" "$TESS_BIN"
          done

      - name: Package macOS application
        run: zip -r sOCRate-macOS.zip dist/sOCRate.app
        
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: sOCRate-macOS-App
          path: sOCRate-macOS.zip