# .github/workflows/build.yml

name: Build sOCRate Executables

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # --- JOB 1 : CONSTRUCTION POUR WINDOWS ---
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Install Tesseract OCR
        run: choco install tesseract-ocr --params='"/l fra,eng,por"' -y
      - name: Build Windows executable
        run: |
          pyinstaller --windowed --onefile --name sOCRate `
          --icon=assets/icon.ico `
          --add-data "C:/Program Files/Tesseract-OCR;Tesseract-OCR" `
          socrate.py
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: sOCRate-Windows-Executable
          path: dist/sOCRate.exe

  # --- JOB 2 : CONSTRUCTION POUR MACOS (SOLUTION DÉFINITIVE) ---
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Install Tesseract OCR via Homebrew
        run: brew install tesseract tesseract-lang

      - name: Build macOS application
        run: |
          # On trouve le chemin d'installation de Tesseract
          TESSERACT_PREFIX=$(brew --prefix tesseract)
          
          # On compile l'application. On copie le dossier Tesseract ENTIER via --add-data.
          # C'est la méthode la plus fiable pour que tous les fichiers (binaires, libs, data) soient ensemble.
          pyinstaller --windowed --name sOCRate \
          --icon=assets/icon.icns \
          --add-data "$TESSERACT_PREFIX:Tesseract-OCR" \
          --osx-entitlements-file entitlements.plist \
          socrate.py

      # --- ÉTAPE CRUCIALE POUR CORRIGER LES PERMISSIONS ---
      - name: Fix Tesseract permissions after bundling
        run: |
          # On donne explicitement la permission d'exécution au binaire Tesseract
          # qui a été copié à l'intérieur de l'application.
          chmod +x dist/sOCRate.app/Contents/Resources/Tesseract-OCR/bin/tesseract

      - name: Package macOS application
        run: zip -r sOCRate-macOS.zip dist/sOCRate.app
        
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: sOCRate-macOS-App
          path: sOCRate-macOS.zip