# .github/workflows/build.yml

name: Build sOCRate Executables

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # --- JOB 1 : CONSTRUCTION POUR WINDOWS (INCHANGÉ ET CORRECT) ---
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Tesseract OCR
        run: choco install tesseract-ocr --params='"/l fra,eng,por"' -y
      - name: Build Windows executable
        run: |
          pyinstaller --windowed --onefile --name sOCRate `
          --icon=assets/icon.ico `
          --add-data "C:/Program Files/Tesseract-OCR;Tesseract-OCR" `
          socrate.py
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: sOCRate-Windows-Executable
          path: dist/sOCRate.exe

  # --- JOB 2 : CONSTRUCTION POUR MACOS (SOLUTION FINALE AVEC TOUTES LES LANGUES) ---
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Install Tesseract OCR via Homebrew
        run: brew install tesseract # On n'a pas besoin de tesseract-lang

      # NOUVELLE ÉTAPE CRUCIALE : On télécharge manuellement les langues nécessaires
      - name: Download Tesseract Languages
        run: |
          TESSDATA_PATH=$(brew --prefix tesseract)/share/tessdata
          echo "Downloading language files to $TESSDATA_PATH"
          curl -L -o "$TESSDATA_PATH/fra.traineddata" "https://github.com/tesseract-ocr/tessdata_fast/raw/main/fra.traineddata"
          curl -L -o "$TESSDATA_PATH/por.traineddata" "https://github.com/tesseract-ocr/tessdata_fast/raw/main/por.traineddata"
          curl -L -o "$TESSDATA_PATH/eng.traineddata" "https://github.com/tesseract-ocr/tessdata_fast/raw/main/eng.traineddata"
          echo "Vérification des fichiers de langue téléchargés :"
          ls -l "$TESSDATA_PATH"

      - name: Build and Package macOS application
        run: |
          # Cette section ne change plus, elle est correcte
          pyinstaller --windowed --name sOCRate \
          --icon=assets/icon.icns \
          --add-data "$(brew --prefix tesseract):Tesseract-OCR" \
          --osx-entitlements-file entitlements.plist \
          socrate.py
          
          chmod +x "dist/sOCRate.app/Contents/Resources/Tesseract-OCR/bin/tesseract"
          
          sleep 5
          
          hdiutil create dist/sOCRate.dmg -volname "sOCRate" -srcfolder dist/sOCRate.app

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: sOCRate-macOS-DiskImage
          path: dist/sOCRate.dmg