# .github/workflows/build.yml

name: Build sOCRate Application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_macos:
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies (Homebrew)
      run: |
        brew install tesseract
        brew install create-dmg

    # --- ✨ CORRECTION FINALE : On télécharge manuellement les packs de langues ✨ ---
    - name: Download additional language packs for macOS
      run: |
        # On trouve le dossier où Homebrew stocke les données linguistiques
        TESSDATA_DIR=$(brew --prefix tesseract)/share/tessdata
        echo "Downloading language packs to $TESSDATA_DIR..."
        # On télécharge les fichiers manquants
        curl -L -o "$TESSDATA_DIR/fra.traineddata" "https://github.com/tesseract-ocr/tessdata_fast/raw/main/fra.traineddata"
        curl -L -o "$TESSDATA_DIR/por.traineddata" "https://github.com/tesseract-ocr/tessdata_fast/raw/main/por.traineddata"
        echo "Language packs downloaded."

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build macOS Application
      run: |
        TESSERACT_PATH=$(brew --prefix tesseract)
        export LDFLAGS="-L${TESSERACT_PATH}/lib"
        pyinstaller socrate_app.py socrate_engine.py --noconfirm --onedir --windowed \
          --name "sOCRate" \
          --icon "assets/icon.icns" \
          --add-data "assets:assets" \
          --add-data "${TESSERACT_PATH}:Tesseract-OCR" \
          --osx-bundle-identifier "com.amaurypoussier.socrate" \
          --osx-entitlements-file "entitlements.plist" \
          --target-arch arm64
    - name: Create DMG Installer
      run: |
        create-dmg \
          --volname "sOCRate Installer" \
          --window-pos 200 120 \
          --window-size 600 400 \
          --icon-size 128 \
          --icon "sOCRate.app" 175 190 \
          --hide-extension "sOCRate.app" \
          --app-drop-link 425 188 \
          --background "dmg-assets/background.png" \
          "dist/sOCRate.dmg" \
          "dist/sOCRate.app/"
    - name: Upload macOS DMG Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sOCRate-macOS-arm64
        path: dist/sOCRate.dmg

  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Tesseract for Windows via Chocolatey
      run: choco install tesseract -y
    - name: Download additional language packs for Windows
      shell: pwsh
      run: |
        $tessdata_dir = "C:\Program Files\Tesseract-OCR\tessdata"
        Invoke-WebRequest -Uri "https://github.com/tesseract-ocr/tessdata_fast/raw/main/fra.traineddata" -OutFile "$tessdata_dir\fra.traineddata"
        Invoke-WebRequest -Uri "https://github.com/tesseract-ocr/tessdata_fast/raw/main/por.traineddata" -OutFile "$tessdata_dir\por.traineddata"
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build Windows Application
      shell: pwsh
      run: |
        pyinstaller socrate_app.py socrate_engine.py --noconfirm --onedir --windowed `
          --name "sOCRate" `
          --icon "assets/icon.ico" `
          --add-data "assets;assets" `
          --add-data "C:\Program Files\Tesseract-OCR;Tesseract-OCR"
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sOCRate-Windows
        path: dist/sOCRate