# .github/workflows/build.yml

name: Build sOCRate Executables

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # --- JOB 1 : CONSTRUCTION POUR WINDOWS (INCHANGÉ ET CORRECT) ---
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Tesseract OCR
        run: choco install tesseract-ocr --params='"/l fra,eng,por"' -y
      - name: Build Windows executable
        run: |
          pyinstaller --windowed --onefile --name sOCRate `
          --icon=assets/icon.ico `
          --add-data "C:/Program Files/Tesseract-OCR;Tesseract-OCR" `
          socrate.py
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: sOCRate-Windows-Executable
          path: dist/sOCRate.exe

  # --- JOB 2 : CONSTRUCTION POUR MACOS (CORRIGÉ ET ROBUSTE) ---
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Install Tesseract OCR via Homebrew
        # Installe tesseract ET les paquets de langues
        run: brew install tesseract tesseract-lang
      - name: Build macOS application
        run: |
          # CORRECTION CLÉ :
          # Au lieu de copier des fichiers séparés, on copie le dossier Tesseract entier.
          # `brew --prefix tesseract` trouve le dossier d'installation (ex: /opt/homebrew/opt/tesseract).
          # On copie ce dossier DANS l'application, sous le nom "Tesseract-OCR".
          # C'est simple, fiable, et ça inclut l'exécutable, les libs, et les données de langue.
          pyinstaller --windowed --name sOCRate \
          --icon=assets/icon.icns \
          --add-data "$(brew --prefix tesseract):Tesseract-OCR" \
          --osx-entitlements-file entitlements.plist \
          socrate.py
      - name: Package macOS application
        # Il est plus standard de créer un .dmg pour la distribution, mais un .zip fonctionne aussi.
        run: hdiutil create dist/sOCRate.dmg -volname "sOCRate" -srcfolder dist/sOCRate.app
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: sOCRate-macOS-DiskImage
          path: dist/sOCRate.dmg