# .github/workflows/build.yml

name: Build sOCRate Executables

# Déclenche le workflow à chaque push sur la branche 'main' ou manuellement
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # ============================================
  # ===   JOB 1 : CONSTRUCTION POUR WINDOWS  ===
  # ============================================
  build-windows:
    runs-on: windows-latest
    steps:
      # Récupère le code de votre dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installe Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Installe les dépendances Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Installe Tesseract OCR avec les langues nécessaires via Chocolatey
      - name: Install Tesseract OCR
        run: choco install tesseract-ocr --params='"/l fra,eng,por"' -y

      # Compile l'application en un .exe unique
      - name: Build Windows executable
        run: |
          pyinstaller --windowed --onefile --name sOCRate `
          --icon=assets/icon.ico `
          --add-data "C:/Program Files/Tesseract-OCR;Tesseract-OCR" `
          socrate.py

      # Met en ligne l'exécutable pour que vous puissiez le télécharger
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: sOCRate-Windows-Executable
          path: dist/sOCRate.exe

  # ===========================================
  # ===   JOB 2 : CONSTRUCTION POUR MACOS   ===
  # ===========================================
  build-macos:
    runs-on: macos-latest
    steps:
      # Récupère le code de votre dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installe Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Installe les dépendances Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Installe Tesseract OCR et les langues via Homebrew
      - name: Install Tesseract OCR via Homebrew
        run: brew install tesseract tesseract-lang

      # Compile l'application en un .app
      - name: Build macOS application
        run: |
          # On trouve dynamiquement le chemin d'installation de Tesseract pour la robustesse
          TESSERACT_PATH=$(brew --prefix tesseract)
          pyinstaller --windowed --name sOCRate `
          --icon=assets/icon.icns `
          --add-data "$TESSERACT_PATH:Tesseract-OCR" `
          socrate.py

      # Compresse le .app dans un .zip pour faciliter le téléchargement
      - name: Package macOS application
        run: zip -r sOCRate-macOS.zip dist/sOCRate.app

      # Met en ligne le .zip pour que vous puissiez le télécharger
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: sOCRate-macOS-App
          path: sOCRate-macOS.zip