# .github/workflows/build.yml

name: Build sOCRate Application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_macos:
    # --- ✨ MODIFICATION 1 : On demande une machine Apple Silicon (M1/ARM64) ✨ ---
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies (Homebrew)
      run: |
        brew install tesseract tesseract-lang
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build macOS Application
      run: |
        TESSERACT_PATH=$(brew --prefix tesseract)
        pyinstaller socrate_app.py --noconfirm --onedir --windowed \
          --name "sOCRate" \
          --icon "assets/icon.icns" \
          --add-data "assets:assets" \
          --add-data "${TESSERACT_PATH}/bin:Tesseract-OCR/bin" \
          --add-data "${TESSERACT_PATH}/lib:Tesseract-OCR/lib" \
          --add-data "${TESSERACT_PATH}/share/tessdata:Tesseract-OCR/share/tessdata" \
          --osx-bundle-identifier "com.amaurypoussier.socrate" \
          --osx-entitlements-file "entitlements.plist" \
          # --- ✨ MODIFICATION 2 : On force la compilation pour ARM64 uniquement ✨ ---
          --target-arch arm64

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sOCRate-macOS-arm64
        path: dist/sOCRate.app

  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Tesseract for Windows via Chocolatey
      run: choco install tesseract -y
    - name: Download additional language packs
      shell: pwsh
      run: |
        $tessdata_dir = "C:\Program Files\Tesseract-OCR\tessdata"
        Write-Host "Downloading language packs to $tessdata_dir..."
        Invoke-WebRequest -Uri "https://github.com/tesseract-ocr/tessdata_fast/raw/main/fra.traineddata" -OutFile "$tessdata_dir\fra.traineddata"
        Invoke-WebRequest -Uri "https://github.com/tesseract-ocr/tessdata_fast/raw/main/por.traineddata" -OutFile "$tessdata_dir\por.traineddata"
        Write-Host "Language packs downloaded."
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build Windows Application
      shell: pwsh
      run: |
        pyinstaller socrate_app.py --noconfirm --onedir --windowed `
          --name "sOCRate" `
          --icon "assets/icon.ico" `
          --add-data "assets;assets" `
          --add-data "C:\Program Files\Tesseract-OCR;Tesseract-OCR"
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sOCRate-Windows
        path: dist/sOCRate